Support file types
jupyterlab/jupyter_collaboration pull request #154
Opened 2023-05-24 16:18 UTC by hbcarlos

Fixes https://github.com/QuantStack/glue-lab/issues/43

2023-05-24 19:44 UTC, davidbrochart requested changes
Thanks @hbcarlos.
LGTM apart from the linter and the type checks.

2023-05-25 07:27 UTC, davidbrochart commented on jupyter_collaboration/loaders.py
> +                self._log.error(f"Error loading metadata from file: {self.path}\n{e!r}", exc_info=e)
What happens if there is an exception? If will fail later because `model` is not defined.

2023-05-25 07:27 UTC, davidbrochart commented on jupyter_collaboration/rooms.py
> +                )
Same here.

2023-05-25 07:28 UTC, davidbrochart commented on jupyter_collaboration/rooms.py
> +
Same here.

2023-05-25 07:28 UTC, davidbrochart commented on jupyter_collaboration/rooms.py
> +
Same here.

2023-05-30 09:04 UTC, trungleduc approved these changes

2023-05-30 09:18 UTC, davidbrochart approved these changes

2023-05-30 09:18 UTC, merged

2023-05-30 09:59 UTC, martinRenou commented
🚀

2023-05-30 10:26 UTC, hbcarlos commented
@trungleduc It is done. Can you try it out? There was an error during the release, and I had to publish the PyPi package manually.

https://github.com/jupyterlab/jupyter_collaboration/releases/tag/v1.0.0alpha9

2023-05-30 10:33 UTC, hbcarlos commented
@fcollonval I tried to publish a new alpha with the release but could not. It failed while publishing the PyPi package. It looks like the jupyter_collaboration project is under the Jupyter organization on PyPi, and my token is not valid anymore. See:
https://github.com/hbcarlos/jupyter_releaser/actions/runs/5120015846/jobs/9205992914#step:6:204

I tried to create a new token with a different scope, but I could not. I'm not sure if it is because I'm not part of the Jupyter org in PyPi or how we should publish the package now.